### ISSUE TITLE
ArgumentError: comparison of NilClass with 0 failed

### ISSUE THREAD

**Issue by jasonkarns** [amatsuda/erd#31]
ArgumentError in Erd::ErdController#index
comparison of NilClass with 0 failed
Extracted source (around line #140):

```              
      }.compact
      max_model_x = models.map {|m| m[:x].to_f + m[:width].to_f }.max
      erd_width = [[(BigDecimal(svg_width) * 72).round, max_model_x].min + 150, 1024].max
      max_model_y = models.map {|m| m[:y].to_f + m[:height].to_f }.max
      erd_height = [[(BigDecimal(svg_height) * 72).round, max_model_y].min + 150, 768].max
      # edge tail head n x1 y1 .. xn yn [label xl yl] style color
```

**Comment by amatsuda** [comment]
@jasonkarns Thank you so much for letting me know the error!

The bug has been fixed via 563b009199e257e961e0c7eca62e29929e2afc18, and a new gem package versioned 0.8.1 including the fix has been released. Thanks! 🙏
